import random

import discord
from helpers import get_gif
from helpers import get_gif, parse, check_admin_permissions

commands = [
    "animal",
    "list",
    "aardvark",
    "aardwolf",
    "african buffalo",
    "african elephant",
    "african elephant",
    "african leopard",
    "african tree pangolin",
    "albatross",
    "alligator",
    "alpaca",
    "american buffalo (bison)",
    "american robin",
    "amphibian",
    "anaconda",
    "angelfish",
    "anglerfish",
    "ant",
    "anteater",
    "antelope",
    "antlion",
    "ape",
    "aphid",
    "arabian horse",
    "arabian leopard",
    "arctic fox",
    "arctic wolf",
    "armadillo",
    "arrow crab",
    "arthropod(s)",
    "asian elephant",
    "asp",
    "ass (donkey)",
    "aye-aye",
    "baboon",
    "badger",
    "bald eagle",
    "bali cattle",
    "bandicoot",
    "bangle tiger",
    "barnacle",
    "barracuda",
    "basilisk",
    "bass",
    "bat",
    "bat(s)",
    "beaked whale",
    "bear",
    "bearded dragon",
    "beaver",
    "bedbug",
    "bee",
    "beetle",
    "beluga whale",
    "bengal tiger",
    "big-horned sheep",
    "billy goat",
    "bird",
    "bird(s)",
    "bison",
    "black bear",
    "black footed rhino",
    "black howler monkey",
    "black panther",
    "black rhino",
    "black widow spider",
    "blackbird",
    "blacktip reef shark",
    "blue bird",
    "blue jay",
    "blue shark",
    "blue whale",
    "blue whale",
    "boa",
    "boar",
    "bob-cat",
    "bobcat",
    "bobolink",
    "bonobo",
    "booby",
    "bottlenose dolphin",
    "bottlenose whale",
    "bovid",
    "box jellyfish",
    "brown bear",
    "buffalo",
    "buffalo, african",
    "buffalo, american (bison)",
    "bug",
    "bull",
    "bull frog",
    "butterfly",
    "buzzard",
    "caiman lizard",
    "camel",
    "canid",
    "canidae",
    "cape buffalo",
    "capuchin monkey",
    "capybara",
    "cardinal",
    "caribou",
    "carp",
    "cat",
    "cat(s)",
    "caterpillar",
    "catfish",
    "catshark",
    "cattle",
    "centipede",
    "cephalopod",
    "chameleon",
    "cheetah",
    "chickadee",
    "chicken",
    "chick",
    "chicks",
    "chicken breeds",
    "chimpanzee",
    "chinchilla",
    "chipmunk",
    "cicada",
    "clam",
    "clownfish",
    "cobra",
    "cockroach",
    "cod",
    "common dolphin",
    "common household pests",
    "common names of poisonous animals",
    "common seal",
    "condor",
    "constrictor",
    "coral",
    "coral(s) and anemone(s)",
    "cougar",
    "cow",
    "cow(s)",
    "coyote",
    "crab",
    "crane",
    "crane fly",
    "crawdad",
    "crayfish",
    "cricket",
    "crocodile",
    "crow",
    "crustacean(s)",
    "cuckoo",
    "damselfly",
    "dart frog",
    "deer",
    "degus",
    "dik-dik",
    "dingo",
    "dinosaur",
    "dog",
    "dog(s)",
    "dogfish shark",
    "dolphin",
    "domestic bactrian camel",
    "domestic canary",
    "domestic dromedary camel",
    "domestic duck",
    "domestic goat",
    "domestic goose",
    "domestic guineafowl",
    "domestic hedgehog",
    "domestic pig",
    "domestic pigeon",
    "domestic rabbit",
    "domestic silkmoth",
    "domestic silver fox",
    "domestic turkey",
    "donkey",
    "door mouse",
    "dormouse",
    "dove",
    "draft horse",
    "dragon",
    "dragonfly",
    "duck",
    "duck breeds",
    "duckbill platypus",
    "dugong",
    "dung beetle",
    "dusky shark",
    "eagle",
    "earthworm",
    "earwig",
    "echidna",
    "eel",
    "egret",
    "elephant",
    "elephant seal",
    "elephant seal",
    "elk",
    "emu",
    "english pointer",
    "ermine",
    "eurasian lynx",
    "falcon",
    "fancy mouse",
    "fancy rat",
    "fancy rat varieties",
    "felidae",
    "ferret",
    "finch",
    "firefly",
    "fish",
    "fish(es)",
    "flamingo",
    "flea",
    "florida panther",
    "fly",
    "flying fox",
    "flyingfish",
    "fowl",
    "fox",
    "fresh water crocodile",
    "frog",
    "fruit bat",
    "fur seal",
    "galapagos land iguana",
    "galapagos shark",
    "galapagos tortoise",
    "galliform",
    "gamefowl",
    "gayal",
    "gazelle",
    "gecko",
    "gerbil",
    "giant anteater",
    "giant panda",
    "giant panda",
    "giant squid",
    "gibbon",
    "gila monster",
    "giraffe",
    "goat",
    "goldfish",
    "goose",
    "goose breeds",
    "gopher",
    "gorilla",
    "grasshopper",
    "gray fox",
    "gray nurse shark",
    "gray reef shark",
    "gray whale",
    "great blue heron",
    "great white shark",
    "great white shark",
    "green poison dart frog",
    "green sea turtle",
    "grizzly bear",
    "grizzly bear",
    "ground shark",
    "ground sloth",
    "groundhog",
    "grouse",
    "guan",
    "guanaco",
    "guinea pig",
    "guinea pig",
    "guineafowl",
    "gull",
    "guppy",
    "haddock",
    "hairy-nosed wombat",
    "halibut",
    "hammerhead shark",
    "hammerhead shark",
    "hamster",
    "harbor porpoise",
    "harbor seal",
    "hare",
    "harp seal",
    "harrier",
    "hawaiian monk seal",
    "hawk",
    "hedgehog",
    "hermit crab",
    "heron",
    "herring",
    "hippopotamus",
    "hookworm",
    "horn shark",
    "hornet",
    "horse",
    "horse(s)",
    "hoverfly",
    "howler monkey",
    "hummingbird",
    "humpback whale",
    "humpback whale",
    "hyena",
    "hyrax",
    "iguana",
    "iguanodon",
    "impala",
    "insect(s)",
    "irrawaddy dolphin",
    "irukandji jellyfish",
    "jackal",
    "jackrabbit",
    "jaguar",
    "jay",
    "jellyfish",
    "junglefowl",
    "kangaroo",
    "kangaroo mouse",
    "kangaroo rat",
    "kermode bear",
    "killer whale",
    "kingfisher",
    "kite",
    "kiwi",
    "koala",
    "koi",
    "komodo dragon",
    "komodo dragon",
    "kookaburra",
    "krill",
    "lab rat",
    "laboratory rat strains",
    "ladybug",
    "lama",
    "lamb",
    "lamprey",
    "lancelet",
    "land snail",
    "landfowl",
    "lark",
    "least weasel",
    "leatherback sea turtle",
    "leech",
    "lemming",
    "lemon shark",
    "lemur",
    "leopard",
    "leopard gecko",
    "leopard seal",
    "leopard shark",
    "leopon",
    "limpet",
    "lion",
    "list",
    "lizard",
    "llama",
    "lobster",
    "locust",
    "loggerhead turtles",
    "loon",
    "louse",
    "lungfish",
    "lynx",
    "macaw",
    "mackerel",
    "magpie",
    "mako shark",
    "mammal",
    "manatee",
    "mandrill",
    "manta ray",
    "manta ray",
    "mantis",
    "marbled salamander",
    "marlin",
    "marmoset",
    "marmot",
    "marsupial",
    "marsupial(s)",
    "marten",
    "mastodon",
    "meadowlark",
    "meerkat",
    "megamouth shark",
    "melon-headed whale",
    "miniature donkey",
    "mink",
    "minke whale",
    "mini pig",
    "minnow",
    "mite",
    "mockingbird",
    "mole",
    "mole salamander",
    "mollusk",
    "mollusk(s)",
    "mongoose",
    "monitor lizard",
    "monitor lizard",
    "monk seal",
    "monkey",
    "moose",
    "mosquito",
    "moth",
    "mountain goat",
    "mountain lion",
    "mouse",
    "mule",
    "muskox",
    "muskrat",
    "naked mole rat",
    "narwhal",
    "nautilus",
    "new world quail",
    "newt",
    "nightingale",
    "northern right whale",
    "nurse shark",
    "nutria",
    "nyala",
    "ocelot",
    "octopus",
    "okapi",
    "old world quail",
    "opossum",
    "orangutan",
    "orca",
    "ostrich",
    "otter",
    "owl",
    "ox",
    "panda",
    "panther",
    "panthera hybrid",
    "parakeet",
    "parrot",
    "parrotfish",
    "partridge",
    "peacock",
    "peafowl",
    "pelican",
    "penguin",
    "perch",
    "peregrine falcon",
    "pheasant",
    "pig",
    "pigeon",
    "pigeon breeds",
    "pike",
    "pilot whale",
    "pilot whale",
    "pine marten",
    "pinniped",
    "piranha",
    "planarian",
    "platypus",
    "polar bear",
    "polar bear",
    "pony",
    "porcupine",
    "porpoise",
    "portuguese man o' war",
    "possum",
    "potbellied pig",
    "potto",
    "prairie dog",
    "prairie dog",
    "prawn",
    "praying mantis",
    "primate",
    "proboscis monkey",
    "przewalski's wild horse",
    "ptarmigan",
    "puffin",
    "puma",
    "pygmy hippopotamus",
    "pygmy right whale",
    "pygmy sperm whale",
    "python",
    "quail",
    "quelea",
    "quokka",
    "quokkas",
    "quolls",
    "rabbit",
    "raccoon",
    "rainbow trout",
    "rat",
    "rattlesnake",
    "raven",
    "ray",
    "ray (batoidea)",
    "ray (rajiformes)",
    "red fox",
    "red kangaroo",
    "red panda",
    "red panda",
    "red-eyed tree frog",
    "reef shark",
    "reindeer",
    "reptile",
    "rhino",
    "rhinoceros",
    "right whale",
    "right whale",
    "ringed seal",
    "ringneck dove",
    "risso's dolphin",
    "river dolphin",
    "roadrunner",
    "rodent",
    "rook",
    "rooster",
    "rosa pig",
    "roundworm",
    "saber-toothed cat",
    "sailfish",
    "salamander",
    "salmon",
    "sandbar shark",
    "sawfish",
    "scale insect",
    "scallop",
    "scalloped hammerhead shark",
    "scorpion",
    "sea lion",
    "sea lion",
    "sea slug",
    "sea snail",
    "sea turtles",
    "seahorse",
    "seal",
    "sei whale",
    "shark",
    "sheep",
    "sheep breeds",
    "shortfin mako shark",
    "shrew",
    "shrimp",
    "siamese fighting fish",
    "siberian tiger",
    "silkworm",
    "silky shark",
    "silverfish",
    "skink",
    "skunk",
    "slender loris",
    "sloth",
    "sloth bear",
    "slug",
    "smelt",
    "snail",
    "snake",
    "snake(s)",
    "snipe",
    "snow fox",
    "snow hare",
    "snow leopard",
    "snow leopard",
    "snow monkey",
    "society finch",
    "sockeye salmon",
    "sole",
    "somali wild ass",
    "sparrow",
    "spectacled bear",
    "sperm whale",
    "sperm whale",
    "spider",
    "spider monkey",
    "spider monkey",
    "spiny dogfish shark",
    "spoonbill",
    "spotted dolphin",
    "squid",
    "squirrel",
    "star-nosed mole",
    "star-nosed mole",
    "starfish",
    "steelhead trout",
    "stellar sea lion",
    "stingray",
    "stoat",
    "stork",
    "striped dolphin",
    "sturgeon",
    "sugar glider",
    "sun bear",
    "swallow",
    "swan",
    "swift",
    "swordfish",
    "swordtail",
    "tahr",
    "takin",
    "tamarin",
    "tapir",
    "tarantula",
    "tarsier",
    "tasmanian devil",
    "tasmanian devil",
    "tasmanian tiger",
    "termite",
    "tern",
    "terrapin",
    "thresher shark",
    "thrush",
    "tick",
    "tiger",
    "tiger salamander",
    "tiger shark",
    "tiger shark",
    "tiglon",
    "toad",
    "topi",
    "tortoise",
    "toucan",
    "trapdoor spider",
    "tree frog",
    "tree frog",
    "trout",
    "tuna",
    "turkey",
    "turkey breeds",
    "turtle",
    "tyrannosaurus",
    "uakari",
    "urial",
    "vampire bat",
    "vampire bat",
    "vampire squid",
    "vancouver island marmot",
    "vervet monkey",
    "vicuna",
    "viper",
    "vole",
    "vulture",
    "wallaby",
    "walrus",
    "warbler",
    "warthog",
    "wasp",
    "water boa",
    "water buffalo",
    "water buffalo",
    "water buffalo breeds",
    "weasel",
    "whale",
    "whale shark",
    "whale(s)",
    "whippet",
    "white rhino",
    "white tailed deer",
    "white-beaked dolphin",
    "whitefish",
    "whitetip reef shark",
    "whooping crane",
    "wildcat",
    "wildebeest",
    "wildfowl",
    "wobbegong shark",
    "wolf",
    "wolverine",
    "wombat",
    "woodchuck",
    "woodpecker",
    "worm",
    "wren",
    "xerinae",
    "yak",
    "yellow perch",
    "yellow-bellied marmot",
    "zebra",
    "zebra finch",
    "zebu",
    "zorilla"
]

requires_mention = False
accepts_mention = False
description = "Gets an animal!"


async def execute(message):
    command, channel, params, mentions, author = parse(message)

    if command == "animal":
        command = random.choice(commands)
    gif = get_gif(command, pos=0, lmt=10, wo_anime=True)

    if gif is None:
        await message.channel.send("Zu diesem Tier gibt es keine Gifs qwq")
    embed = discord.Embed()
    embed.description = command.replace("+", "")
    embed.set_image(url=gif)
    await message.channel.send(embed=embed)
