name: 'Build Container Images'

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: vincentscode
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        builder: ${{ steps.buildx.outputs.name }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/vincentscode/extendedkawaiibot:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
